services:
  app:
    image: alstjr971/cicd-study:latest
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: dev
  jenkins:
    image: jenkins/jenkins:2.471-jdk21
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - ${HOST_JENKINS_HOME}:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

    links:
      - worker-1

  worker-1:
    image: jenkins/ssh-agent:latest-jdk21
    volumes:
      - ${HOST_JENKINS_WORKER_1}:/home/jenkins
    environment:
      - JENKINS_SLAVE_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC1nwX/j1qBIcxxxcviXRK2Teqe7rh03LKW+9dtTh10EFxYwwoU7jDw2Bk705ZUHxFGN5J9PFeZoqLi1AvkkdsCkitaL8wuTStWra/JZpAK0jUB0R1V5UTbCsKICtq1aPeMn6niTn19hskJWWmvt8tuS4QRG9ssHQK91EDSyhYZe/6iPK+klnySvy/TUxHp0YzZSLeSOH3ajAIJh5rA0zMgA+zEaxlL6AO/N3tVXEyARJjRuXtMSXE5VBqdY3FRM6IHIxcz/serLIx96Q9oIWhn+5YQp/qlV00fo0id0EaElLiwY8B2qWZXZ5D9Of0kq0TTAlWBqTEzUYAugfeEqg+regAIhJhwOn+BHeN0SiEr9LAZlsWNA81VUfy4rrcCuNHsf451pu248ywPVs9/fcgIqmR2AFjDaWjZQwiaw1THz9pvfwwF1garaGIfoHGG3Juz+CnRl55ED9LpYy7ir0+VP80iUA1xXeh3QRHmy/XW32ZeKZcwwRH0O+gNc76j0os=

  sonarqube:
    image: sonarqube:9-community
    ports:
      - "9000:9000"
